Mentally/urls.py
# testing 
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('counsellor/',include('counsellor.urls')),
    path('',include('client.urls')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

client/urls.py
from django.urls import path
from . import views
from django.shortcuts import render, redirect

from rest_framework import routers

from rest_framework_jwt.views import obtain_jwt_token

# from counsellor.urls import
    
# router = routers.DefaultRouter()

# router.register('api/talk',views.TalkViewSet,'talk-api')

urlpatterns = [
    path('', views.home, name = "client-home"),
    path('about/',views.about, name="client-about"),
    path('talk/',views.talk,name = "talk-to-counsellor"),
    path('signup/',views.signup,name="sign-up"),
    path('update-profile/',views.updateProfile,name="update-profile"),

    path('edit-profile/',views.editProfileClient,name="edit-profile"),
    path('edit-profile-counsellor/',views.editProfileCounsellor,name="edit-profile-counsellor"),

    path('delete-description/<int:pk>/',views.deleteDescription,name="delete-description"),
    path('delete-booking/<int:pk>/',views.deleteBooking,name="delete-booking"),

    path('report/',views.reportProblem,name='report'),


    path('my-profile/',views.myProfile,name="my-profile"),
    path('counsellor-profile/<int:pk>/',views.counsellorProfile,name="counsellor-profile"),
    # path('accounts/login/',views.login,name='login'),
    # path('accounts/logout/',views.logout,name='log-out'),
    path('profile/<int:pk>/',views.profile,name='profile'),
    path('pick/',views.pick,name = "pick-clients"),
    path('active/',views.active,name = "active-clients"),
    path('active-sessions/',views.sessions,name="active-sessions"),
    path('update-profile-counsellor',views.editProfileCounsellor,name="update-profile-counsellor"),
    path('book/<int:pk>/',views.book,name="book-appointment"),
    path('FAQs/',views.faqs,name="faqs"),
    #path('blog/',views.blog,name="blog"),
    path('blog/', views.blogListView, name="blog"),
    path('blog/blog_detail/<int:pk>/',views.blogDetailView,name="blog_detail"),
    path('blog/add_post/',views.createPostView,name="add_post"),
    path('blog/personal-blogs/',views.personalBlogListView,name="personal-blogs"),
    path('blog/delete-blog/<int:pk>/',views.deleteBlog,name="delete-blog"),
    path('blog/update-blog/<int:pk>/',views.updateBlogView,name="update-blog"),

    path('messages/',views.messages,name = "messages"),
    path('messages-detail/<int:pk>/',views.messageDetail,name = "message-detail"),
    path('videocall/',views.videoCall,name = "video-call"),
    path('connect-client/<int:pk>/',views.interfaceClient,name="connect-client"),
    path('connect-counsellor/<int:pk>/',views.interfaceCounsellor,name="connect-counsellor"),
    path('delete-link/<int:pk>/',views.deleteLink,name="delete-link"),

    path('view-description/<int:pk>',views.clientDescription,name='view-description'),
    path('session-notes/<int:pk>',views.sessNotes,name='session-notes'),
    path('view-notes/<int:pk>',views.viewSessNotes,name='view-notes'),
    path('delete-notes/<int:pk>',views.delSessNotes,name='delete-notes'),
    path('logout/',views.LogOut,name='logout'),
    path('login/',views.LogIn,name='login'),
    
    # API URLS
    #api auth
    
    path('api/signup/',views.CreateUserView.as_view(),name='signup-api'),
    path('api/create-profile/',views.CreateClientProfileView.as_view(),name="create-profile-api"),
    path('api/create-profile-counsellor/',views.CreateCounsellorProfileView.as_view(),name="create-profile-counsellor-api"),
   
    path('api/create-description/',views.CreateDescriptionView.as_view(),name="create-description-api"),
    path('api/list-description/<int:pk>/',views.GetDescriptionView,name="list-description-api"),
    
    path('api/check/',views.UserTypeCheck,name='check'),
    path('api/list-counsellors/',views.ListCounsellorsView.as_view(),name="list-counsellors"),
    path('api/get-userid/',views.GetUserId,name="get-user-id"),
   
    path('api/get-client/<int:pk>/',views.GetClientView,name="get-client"),
    path('api/get-counsellor/<int:pk>/',views.GetCounsellorView,name="get-counsellor"),
   
    path('api/update-profile-counsellor/',views.UpdateCounserllorProfileView.as_view(),name="update-profile-counsellor-api"),
    path('api/update-profile/',views.UpdateClientProfileView.as_view(),name="update-profile-api"),
   
    path('api/book/',views.CreateBookingView.as_view(),name="book"),
    path('api/active-clients/',views.GetActiveClientsView,name="active-clients-api"),
    path('api/active-counsellors/',views.GetActiveCounsellorsView,name="active-counsellors-api"),

    path('api/logout/',views.LogOutView,name="logout-api"),
    path('api/login/',views.LogInView.as_view(),name="login-api"),

    path('api/token-auth/',obtain_jwt_token),
    path('api/current-user/',views.current_user,name ="current-user")

]

# urlpatterns = urlpatterns+router.urls

t/t/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('',include('first.urls')),
    path('admin/', admin.site.urls),
]

client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
# Create your models here.

# CLIENT MODELS

class Clientdata(models.Model):
    User = models.OneToOneField(User,on_delete=models.SET_NULL, null=True, blank=True)
    # user_id = models.IntegerField(null = True,blank = True)
    Name=models.CharField(max_length=100)
    Gender=models.CharField(max_length=32,choices=[('Male','Male'),('Female','Female'),('Others','Others')])
    Age=models.IntegerField(null = True)
    Email=models.EmailField(null = True)
    State=models.CharField(max_length=50,blank = True,null=True)
    City=models.CharField(max_length=50,blank = True,null=True)
    Marital_Status=models.CharField(max_length=32,choices=[('Single','Single'),('Commited','Commited'),('Divorced','Divorced'),('Married','Married')])
    Educational_Status=models.CharField(max_length=32,choices=[('10th Pass','10th Pass'),('12th Pass','12th Pass'),('Graduate','Graduate'),('Post_Graduate','Post_Graduate'),('Doctorate','Doctorate'),('Post_Doc','Post_Doc')])
    
    def __str__(self):
        return self.Name

class Description(models.Model):
    # Email=models.ForeignKey(Clientdata,on_delete=models.CASCADE)
    User = models.OneToOneField(User,on_delete=models.SET_NULL, null=True, blank=True)
    Message=models.CharField(max_length=1000) 

    def __str__(self):
        return self.Message

class sessionNotes(models.Model):
    client = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='sess_cl')
    counsellor = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='sess_coun')
    title = models.CharField(max_length = 200,blank = True,null = True)
    time = models.DateTimeField(null = True,auto_now = True)
    fileurl = models.TextField(default='-')
    filename = models.TextField(default='-')
    about = models.TextField(null = True,blank = True)


class VideoCallLink(models.Model):
    counsellor =  models.OneToOneField(User,on_delete=models.SET_NULL,null=True)
    client =  models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='cl_video')
    link = models.TextField()

    def __str__(self):
        return self.link



class ActiveBookings(models.Model):
    client = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='client_id')
    counsellor = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='counsellor_id') 
    Booking_time = models.TimeField(null=True,auto_now=False, auto_now_add=False)       


class Bookings(models.Model):
    client = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='client_user')
    client_key = models.IntegerField(blank = True,null=True)
    counsellor = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='counsellor_user')
    counsellor_key = models.IntegerField(blank=True,null = True)
    Booking_time = models.TimeField(null=True,auto_now=False, auto_now_add=False)
# COUNSELLOR MODELS

class Counsellordata(models.Model):
    User = models.OneToOneField(User,on_delete=models.SET_NULL, null=True, blank=True)
    # user_id = models.IntegerField(null = True,blank = True)
    Name = models.CharField(max_length=100)
    Gender=models.CharField(max_length=32,choices=[('Male','Male'),('Female','Female'),('Others','Others')])
    Age=models.IntegerField(blank = True,null=True)
    profilepicurl = models.TextField(default='-')
    profilepicname = models.TextField(default='-')
    Email=models.EmailField()
    State=models.CharField(max_length=50,blank=True,null=True)
    City=models.CharField(max_length=50,blank=True,null=True)
    Education=models.CharField(max_length=300,blank = True,null=True)
    Expertise = models.CharField(max_length=200,blank=True,null=True)
    Summary = models.CharField(max_length=1000,blank=True,null=True)
    Consultation_start = models.TimeField(null=True,auto_now=False, auto_now_add=False)
    Consultation_end = models.TimeField(null=True,auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.Name



class Message(models.Model):
    sender = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='sender')   
    reciever = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='reciever')
    body = models.TextField()
    time = models.DateTimeField(null = True,auto_now = True)

    def __str__(self):
        return self.body

class ActiveMessages(models.Model):
    sender = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='active_sender')   
    reciever = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='active_reciever')            

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    time = models.DateTimeField(null = True,auto_now = True)
    body = models.TextField()
    brief = models.TextField(null = True)
    picurl = models.TextField(default='-')
    picname = models.TextField(default='-')

    def __str__(self):
        return self.title + '|' + str(self.author)


class Motivation_small(models.Model):
    title = models.TextField(default='-')
    brief = models.TextField(default='-')
    picture = models.FileField(upload_to='client/uploads',null=True,blank=True)
    article_link = models.TextField(default='-')

    def __str__(self):
        return self.title


class Motivation_large(models.Model):
    quote1 = models.TextField(default='-')
    quote2 = models.TextField(default='-')
    picture = models.FileField(upload_to='uploads',null=True,blank=True)
    article_link = models.TextField(default='-')

    def __str__(self):
        return self.quote1  

class Extra_info(models.Model):
    title =  models.TextField(default='-')
    content = models.TextField(default='-')  

    def __str__(self):
        return self.title   

class About_us_big(models.Model):
    title = models.TextField(default='-')
    content = models.TextField(default='-')
    picture = models.FileField(upload_to = 'uploads',null=True,blank=True)

    def __str__(self):
        return self.title

class About_us_small(models.Model):
    title = models.TextField(default='-')
    content = models.TextField(default='-')

    def __str__(self):
        return self.title

class FAQ_big(models.Model):
    title = models.TextField(default='-')
    content = models.TextField(default='-')
    picture = models.FileField(upload_to = 'uploads',null=True,blank=True)

    def __str__(self):
        return self.title

class FAQ_small(models.Model):
    title = models.TextField(default='-')
    content = models.TextField(default='-')

    def __str__(self):
        return self.title        

class Team_details(models.Model):
    Name = models.CharField(max_length=200)
    Position = models.CharField(max_length=200)
    email = models.CharField(max_length=300)
    picture = models.FileField(upload_to = 'uploads',null=True,blank=True)
    website = models.TextField(default='-')

    def __str__(self):
        return self.Name

class Problem_reports(models.Model):
    title = models.TextField(default = '-')
    brief = models.TextField(default='-')

    def __str__(self):
        return self.title

class Queries(models.Model):
    question = models.TextField(default = '-')

    def __str__(self):
        return self.question        

client/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

# class DescriptionForm(forms.Form):
#     Message=forms.CharField(label = "Message", max_length=1000,help_text="Write your heart out !!!") 
#     extra_data=forms.FileField(label = "extra_data",required=False)

# class UpdateProfileForm(forms.Form):
#     Name=forms.CharField(label = "Name *",max_length=100,help_text="Set an alias if you do not wish to disclose your name")
#     Gender=forms.ChoiceField(label = "Gender *",choices=(('','Gender'),('0','Male'),('1','Female'),('2','Others')))
#     Age=forms.IntegerField(label = "Age *")
#     Email=forms.EmailField(label = "Email *",help_text="Will remain confidential")
#     State=forms.CharField(label = "State",max_length=50,required=False)
#     City=forms.CharField(label = "City",max_length=50,required=False)
#     Marital_Status=forms.ChoiceField(label = "Marital Status *",choices=(('','Marital Status'),('0','Single'),('1','Commited'),('2','Divorced'),('3','Married')))
#     Educational_Status=forms.ChoiceField(label = "Educational Status *",choices=(('','Educational Status'),('0','10th Pass'),('1','12th Pass'),('2','Graduate'),('3','Post-Graduate'),('4','Doctorate'),('5','Post-Doc')))

class DescriptionForm(ModelForm):
    class Meta:
        model = Description
        fields = ['Message']

class UpdateProfileForm(ModelForm):
    class Meta:
        model = Clientdata
        fields = ['Name','Gender','Age','Email','State','City','Marital_Status','Educational_Status']


class UpdateProfileFormCounsellor(ModelForm):
    class Meta:
    	model = Counsellordata
    	fields = ['Education','Expertise','Summary','Consultation_start','Consultation_end']        

class BookingForm(ModelForm):
	class Meta:
		model = ActiveBookings
		fields = ['Booking_time']

client/templates/client/about_us.html
{%extends "client/base.html"%}
<!--
	Mentally by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->


{%block home_state%}<li >{%endblock%}
{%if client%}}  
{%block talk_state%}<li>{%endblock%}
{%block session_state%}<li>{%endblock%}
{%else%}
{%block client_state%}<li>{%endblock%}
{%block active_state%}<li>{%endblock%}  
{%endif%}   
{%block faqs_state%}<li>{%endblock%}
{%block blog_state%}<li>{%endblock%}
    {%block message_state%}<li>{%endblock%}
{%block about_state%}<li class="active">{%endblock%}

{%block content%}

<!-- Post -->
	<section class="post">
	<header class="major">
		<span class="date"><b>{% now "jS F Y H:i" %}</b></span>
		<h1>About Us</h1>

	{%for info in about_us_large%}	
        <p><b><i>{{info.title}}</i></b></p>
	</header>
    {%if info.picture%}
	<div class="image main"><img src="/client/media/{{info.picture}}" alt="" height="600" width="800" /></div>
    {%endif%}
	<p>{{info.content}}</p>
    {%endfor%}
	<div class="expert_doctors_area p-0">
        <div class="container">
            <div class="row justify-content-center ">
                <div class="col-lg-6">
                    <div class="section_title mb-55 text-center">
                        <h3 style="text-align:center;">Our Team</h3>
                    </div>
                </div>
            </div>
            {%for person in our_team%}
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-6">
                    <div class="single_expert">
                        <div class="expert_thumb">
                            <img src="/client/media/{{person.picture}}" alt="" height="300" width="300">
                        </div>
                        <div class="experts_name text-center">
						<center>
                            <h3>{{person.Name}}</h3>
                            <span>{{person.Position}}</span>
							</center>
                            <div class="social_links">
                                <ul>
                                    <li>{{person.email}}
                                        
                                    </li>
                                    <li><i class="fa fa-globe"></i>
                                        <a href="{{person.website}}"> Website</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
                
            </div>
        </div>
    </div>
	{%for info in about_us_small%}
    <div class="dsa">
		<h3>{{info.title}}</h3>
		<p>{{info.content}}</p>
    </div>
    {%endfor%}
    <div class="admin">
        <h3>Administration</h3>
        <p>This site is solely governed by the Administration of IIT Ropar,Counseling Cell</p>
        <ul>
            <li><a target="_blank" href="https://www.facebook.com/iitrpr/">Facebook</li>
            <li><a target="_blank" href="https://twitter.com/iitrpr">Twitter</li>
            <li><a target="_blank" href="https://www.instagram.com/iitropar/">Instagram</li>
            <li><a target="_blank" href="https://www.linkedin.com/company/iitropar">Linkedin</li>
        </ul>
    </div>
    <div class="developers">
        <h3>Contributors</h3>
        <ul><b>
            <li><a target="_blank" href="https://www.linkedin.com/in/ayush-agrawal-iitrpr/">Ayush Agrawal</a></li>
            <li><a target="_blank" href="https://www.linkedin.com/in/divyanshu-mathpal-5a029b17b/">Divyanshu Mathpal</a></li>
            <li><a target="_blank" href="https://www.linkedin.com/in/samreet-singh-dhami-048a71195/">Samreet Singh Dhami</a></li>
        </b>
        </ul>
    </div>
	</section>

{%endblock%}

client/templates/client/active_sessions.html
{%extends "client/base.html"%}
<!--
	Mentally by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->


 {%block intro%}{%endblock%}
				
 {%block home_state%}<li>{%endblock%}
 {%block talk_state%}<li>{%endblock%}
 {%block session_state%}<li class = "active">{%endblock%}	
 {%block faqs_state%}<li>{%endblock%}
 {%block blog_state%}<li>{%endblock%}
 	{%block message_state%}<li>{%endblock%}
 {%block about_state%}<li>{%endblock%}


 {%block content%}

 <!-- Post -->
	


	<section class="posts">

		{%for counsellor,time in all_counsellors%}
			<article>
				<header>
					<!-- <span class="date">April 24, 2017</span> -->
					<h2><a href="#">{{counsellor.Name}}</a></h2>
				</header>
				<p><b>Booking Time: {{time}}</b></p>
				<ul class="actions">
					<li><a onclick="return confirm('Are you sure you want to delete this?')" href="{%url 'delete-booking' counsellor.User.id%}" class="button small">Delete</a></li>
					<li><a href="{%url 'message-detail' pk=counsellor.User.id %}" class="button special">Message</a></li>
					<li><a href="{%url 'connect-counsellor' pk=counsellor.User.id %}" class="button special">Video Call</a></li>

				</ul>
			</article>
		{%endfor%}	
			
		</section>

{%endblock%}

client/templates/client/book.html
{%extends "client/base.html"%}


 {%block intro%}{%endblock%}
				
 {%block home_state%}<li>{%endblock%}
 {%block talk_state%}<li>{%endblock%}
 {%block session_state%}<li>{%endblock%}
 {%block faqs_state%}<li>{%endblock%}
 {%block blog_state%}<li>{%endblock%}
 	{%block message_state%}<li>{%endblock%}
 {%block about_state%}<li>{%endblock%}

 {%block content%}

 <h2>{{counsellor.Name}} is availaible from {{counsellor.Consultation_start}} to {{counsellor.Consultation_end}}</h2>

 <h3>Please pick a time that fits your schedule</h3>

 <centre>Please enter the time in 24-hour format ie. hh:mm</centre>

 <form method="POST">
 	{%csrf_token%}
   <div class="table-wrapper">
		<table>
			{{form.as_table}}
		</table>
	</div>

	<div class="12u$">
		<ul class="actions" align="centre">
			<li><input type="submit" value="Book Now!"  class="special" /></li>
		</ul>
	</div>



 </form>


 {%endblock%}

client/templates/client/edit-description.html
{%extends "client/base.html"%}


{%block home_state%}<li >{%endblock%}
{%if client%}}  
{%block talk_state%}<li>{%endblock%}
{%block session_state%}<li>{%endblock%}
{%else%}
{%block client_state%}<li>{%endblock%}
{%block active_state%}<li>{%endblock%}  
{%endif%}   
{%block faqs_state%}<li>{%endblock%}
{%block blog_state%}<li>{%endblock%}
{%block message_state%}<li>{%endblock%}
{%block about_state%}<li>{%endblock%}

{%block content%}


{%endblock%}

client/templates/client/faqs.html
{%extends "client/base.html"%}
<!--
	Mentally by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->


{%block home_state%}<li >{%endblock%}
{%if client%}}  
{%block talk_state%}<li>{%endblock%}
{%block session_state%}<li>{%endblock%}
{%else%}
{%block client_state%}<li>{%endblock%}
{%block active_state%}<li>{%endblock%}  
{%endif%}   
{%block faqs_state%}<li class="active">{%endblock%}
{%block blog_state%}<li>{%endblock%}
{%block message_state%}<li>{%endblock%}
{%block about_state%}<li>{%endblock%}

{%block content%}

<!-- Post -->
	<section class="post">
	<header class="major">
		<span class="date">{% now "jS F Y H:i" %}</span>
		<h1>FAQs,Facts and Ask</h1>
		<p></p>
	</header>

    {%for post in faq_big%}
    {%if post.picture%}
    <div class="image main"><img src="/client/media/{{post.picture}}" alt="" height="300" width="600" /></div>
    {%endif%}
    <h3>{{post.title}}</h3>
    <p>{{post.content}}</p>
    {%endfor%}


    {%for post in faq_small%}
    <h3>{{post.title}}</h3>
    <p>{{post.content}}</p>
    {%endfor%}

    {%if message%}
<script>
    alert('{{ message }}');
    </script>
{%endif%}

    
    
    <form method="post">
    <h3>You can ask your question here-</h3>
        {%csrf_token%}
        <input type="text" id="Question" name="Question" placeholder="What's on your mind?"><br>
        <br>
        <input type="submit" value="Submit">
        <input type="reset">
    </form>




	</section>

{%endblock%}

client/templates/client/home.html
{%extends "client/base.html"%}


{% block intro %}
	<div id="intro">
		<h1>Here4U</h1>
		<p>An online counselling platform designed by the students of <a href="http://www.iitrpr.ac.in">IIT Ropar.</a><br />
		</p>
		<ul class="actions">
			<li><a href="#header" class="button icon solo fa-arrow-down scrolly">Continue</a></li>
		</ul>
	</div>
{% endblock %}	

				
{%block home_state%}<li class="active">{%endblock%}
{%if client%}}	
{%block talk_state%}<li>{%endblock%}
{%block session_state%}<li>{%endblock%}
{%else%}
{%block client_state%}<li>{%endblock%}
{%block active_state%}<li>{%endblock%}	
{%endif%}
{%block faqs_state%}<li>{%endblock%}	
{%block blog_state%}<li>{%endblock%}
{%block message_state%}<li>{%endblock%}
{%block about_state%}<li>{%endblock%}
				<!-- Main -->

{% block content %}

	<!-- Featured Post -->
		{%if user.is_authenticated%}
		<header class="major">
		
        <ul class="actions">
                
                <li><a href="{% url 'my-profile' %}" class="button big">My Profile</a></li>
                
        </ul>
	</header>
	{%endif%}

		{%for motivation in motivation_large%}
		<article class="post featured">
			<header class="major">
				<span class="date">{% now "jS F Y H:i" %}</span>
				<h2><a href="#">{{motivation.quote1}}</a></h2>
				<p>{{motivation.quote2}}</p>
			</header>
			{%if motivation.picture%}
			<a href="#" class="image main"><img src="/client/media/{{motivation.picture}}" alt="" /></a>
			{%endif%}
			<ul class="actions">
				<li><a href="{{motivation.article_link}}" target="_blank" class="button big">Full Story</a></li>
			</ul>
		</article>
		{%endfor%}

	<!-- Posts -->
		<section class="posts">
			{%for motivation in motivation_small%}
			<article>
				<header>
					<h2><a href="{{motivation.article_link}}">{{motivation.title}}</a></h2>
				</header>
				<a href="#" class="image fit"><img src="/client/media/{{motivation.picture}}" alt="" /></a>
				<p>{{motivation.brief}}</p>
				<ul class="actions">
					<li><a href="{{motivation.article_link}}" target="_blank" class="button">Full Story</a></li>
				</ul>
			</article>
			{%endfor%}
			
			
		</section>
		
		{%for info in extra_content%}
		<section>
		<h2>{{info.title}}</h2>
			<p>{{info.content}}</p>
		</section>
		{%endfor%}




{% endblock %}

					

				

client/templates/client/message-detail.html
{%extends "client/base.html"%}


{%block home_state%}<li >{%endblock%}
{%if client%}}  
{%block talk_state%}<li>{%endblock%}
{%block session_state%}<li>{%endblock%}
{%else%}
{%block client_state%}<li>{%endblock%}
{%block active_state%}<li>{%endblock%}  
{%endif%}   

{%block blog_state%}<li>{%endblock%}
	{%block message_state%}<li>{%endblock%}
{%block about_state%}<li>{%endblock%}


{%block content%}



<div id = "main">

	{%if convo.has_next %}
	<ul class = "actions fit">
		<li><a href="?page={{ convo.next_page_number }}" class = "button fit small">Older messages</a></li>

	</ul>
	{%endif%}
	<p>

 {%for mess in message_list%}

 <b>{{mess.sender.first_name}}: </b> {{mess.body}}
	<br/>


 {%endfor%}

</p>
	
{%if convo.has_previous %}
<ul class = "actions fit">
		<li><a href="?page={{ convo.previous_page_number }}" class = "button fit small">Newer messages</a></li>
	</ul>
{%endif%}
<form method="POST">
	{% csrf_token %}

	<ul class = "actions fit">
		<li><textarea type="text" name="message-body" placeholder="Enter message" rows="1" ></textarea></li>
		<li><input type="submit" class = "button special " value="Send Message" /></li>

	</ul>
	

</form>
</div>


{%endblock%}